//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emlaksitesi.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ajans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ajans()
        {
            this.detay = new HashSet<detay>();
        }
    
        public int kisi_id { get; set; }
        public string profil_resim { get; set; }
        public string gorev { get; set; }
        public string aciklama { get; set; }
        public string ad_soyad { get; set; }
        public string twitter { get; set; }
        public string facebook { get; set; }
        public string instagram { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detay> detay { get; set; }
    }
}
