//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emlaksitesi.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class anasayfa
    {
        public int id { get; set; }
        public string baslik { get; set; }
        public string resim1 { get; set; }
        public string resim2 { get; set; }
        public string resim3 { get; set; }
        public string resim4 { get; set; }
        public string resim5 { get; set; }
    }
}
