//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emlaksitesi.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class bize_ulasin
    {
        public int id { get; set; }
        public string arkaplan_resim { get; set; }
        public string konum_baslik { get; set; }
        public string konum_aciklama { get; set; }
        public string saatBaslik { get; set; }
        public string hizmet_saatleri { get; set; }
        public string email_baslik { get; set; }
        public string email { get; set; }
        public string telefon_baslik { get; set; }
        public long telefon_numarasi { get; set; }
    }
}
