//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emlaksitesi.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class detay
    {
        public int id { get; set; }
        public string ev_resim1 { get; set; }
        public string ev_resim2 { get; set; }
        public string ev_resim3 { get; set; }
        public string aciklama { get; set; }
        public Nullable<int> kisidetay { get; set; }
        public Nullable<int> ev_id { get; set; }
    
        public virtual ajans ajans { get; set; }
        public virtual slider slider { get; set; }
    }
}
