//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emlaksitesi.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class footer
    {
        public int id { get; set; }
        public string baslik { get; set; }
        public string adres { get; set; }
        public Nullable<long> telefon_numarasi { get; set; }
        public string email { get; set; }
        public string instagram { get; set; }
        public string twitter { get; set; }
        public string facebook { get; set; }
    }
}
