//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emlaksitesi.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class hakkimizda
    {
        public int id { get; set; }
        public string baslik { get; set; }
        public string aciklama { get; set; }
        public string arkaplan_resim { get; set; }
        public string alt_baslik1 { get; set; }
        public string aciklama1 { get; set; }
        public string alt_baslik2 { get; set; }
        public string aciklama2 { get; set; }
        public string alt_baslik3 { get; set; }
        public string aciklama3 { get; set; }
        public string resim { get; set; }
    }
}
