//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emlaksitesi.Models.database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class emlakEntities : DbContext
    {
        public emlakEntities()
            : base("name=emlakEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ajans> ajans { get; set; }
        public virtual DbSet<anasayfa> anasayfa { get; set; }
        public virtual DbSet<bize_ulasin> bize_ulasin { get; set; }
        public virtual DbSet<detay> detay { get; set; }
        public virtual DbSet<hakkimizda> hakkimizda { get; set; }
        public virtual DbSet<mesaj> mesaj { get; set; }
        public virtual DbSet<slider> slider { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<yonetim> yonetim { get; set; }
        public virtual DbSet<footer> footer { get; set; }
    }
}
