//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emlaksitesi.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class slider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public slider()
        {
            this.detay = new HashSet<detay>();
        }
    
        public int slider_id { get; set; }
        public string baslik { get; set; }
        public string resim { get; set; }
        public Nullable<int> fiyat { get; set; }
        public string adres { get; set; }
        public string ilce { get; set; }
        public string sehir { get; set; }
        public Nullable<int> yatak_sayisi { get; set; }
        public Nullable<int> banyo_sayisi { get; set; }
        public string durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detay> detay { get; set; }
    }
}
